# General Jekyll Config
highlighter: pygments
baseurl: http://rcmachado.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#2a9520'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: rcmachado
    bitbucket: rcmachado
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: rcmachado
    #facebook: zuck
    #tumblr: animalygifs
    linkedin: rcmachado
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Rodrigo Machado
  email: rcmachado@gmail.com
  tagline: "Just another programmer"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-10254127-3

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
